name: ai_smart_health
dependencies:
  - python=3.9
  - numpy
  - pandas
  - pip
  - scikit-learn
  - seaborn
  - shap
  - tensorflow
  - tqdm
  - pytest
  - pip:
    - jupyter
    - lifelines
    - matplotlib
    - opencv-python
    - pydotplus
    - spyder>=5.*
    - lightgbm
